"""PRISM Engine - Parent Machine Module.

Financial constraint solver and parent-side family scoring engine.
"""

from .config import ParentSolverConfig, DEFAULT_CONFIG
from .models import (
    ParentProfile,
    Route,
    SectorRatings,
    ViabilityReport,
    SubScores,
    BlockedRouteInfo,
    CareerEvaluation,
    ParentEvaluationRequest,
    ParentEvaluationResponse,
    gl_to_risk,
)
from .solver import (
    calculate_net_cost,
    calculate_cash_available,
    calculate_loan_needed,
    calculate_emi,
    calculate_repayment_burden,
    calculate_debt_service_ratio,
    calculate_family_affordability,
    check_financial_gate,
    calculate_grant_shortfall,
)
from .scores import (
    clamp,
    score_budget,
    score_repayment_burden,
    score_debt_service_ratio,
    calculate_payback,
    score_payback,
    score_financial,
    score_domain,
    score_sector,
    score_salary,
    score_time,
    score_location,
    score_aspiration,
    score_risk,
    score_family,
    evaluate_route,
    evaluate_parent_portfolio,
)

__all__ = [
    "ParentSolverConfig",
    "DEFAULT_CONFIG",
    "ParentProfile",
    "Route",
    "SectorRatings",
    "ViabilityReport",
    "SubScores",
    "BlockedRouteInfo",
    "CareerEvaluation",
    "ParentEvaluationRequest",
    "ParentEvaluationResponse",
    "gl_to_risk",
    "calculate_net_cost",
    "calculate_cash_available",
    "calculate_loan_needed",
    "calculate_emi",
    "calculate_repayment_burden",
    "calculate_debt_service_ratio",
    "calculate_family_affordability",
    "check_financial_gate",
    "calculate_grant_shortfall",
    "clamp",
    "score_budget",
    "score_repayment_burden",
    "score_debt_service_ratio",
    "calculate_payback",
    "score_payback",
    "score_financial",
    "score_domain",
    "score_sector",
    "score_salary",
    "score_time",
    "score_location",
    "score_aspiration",
    "score_risk",
    "score_family",
    "evaluate_route",
    "evaluate_parent_portfolio",
]
